baseURL = "https://kodl책dan.se/"
languageCode = "en-us"
title = "Kodl책dan"
theme = "lekh"

[params]
Name = "Kodl책dan"
About = """
Hi there! I'm Carl, contractor at Kodl책dan and senior software developer based in Sweden.
"""
Email = "claeskent@gmail.com"
Resume = "" # Add the filename with file extension.
PostLimit = 4 # Sets the number of posts to display on the front page
GoatCounterCode = ""

[[params.profiles]]
name = "GitHub"
url = "https://github.com/cbring"

#[[params.profiles]]
#name = "Twitter"
#url = "https://twitter.com/username"

[[params.profiles]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/carl-bring/"
